# Docker internal DNS resolver for dynamic name resolution
resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    charset utf-8;
    
    server_name _;
    root /var/www/html/public;

    index index.php index.html;

    location / {
        # Fallback to Laravel front controller when static file is not found
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
